-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: a11d9314b22d8f8c7556443875b731ef05965464
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: end-of-file-fixer
        exclude: '^.+?\.json.+?\.yml$'
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
