steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'k8s/images/app/Dockerfile',
      '--cache-from', 'gcr.io/$PROJECT_ID/learningequality-studio-app:latest',
      '-t', 'gcr.io/$PROJECT_ID/learningequality-studio-app:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/learningequality-studio-app:latest',
      '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
     '-f', 'k8s/images/nginx/Dockerfile',
     '--cache-from', 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:latest', 
     '-t', 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:$COMMIT_SHA',
     '-t', 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:latest',
     '.'
     ]
timeout: 1800s
images:
  - 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:latest'
  - 'gcr.io/$PROJECT_ID/learningequality-studio-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/learningequality-studio-app:latest'
