version: '3.4'

x-studio-environment:
  &studio-environment
    MPLBACKEND: ps
    SHELL: /bin/bash
    AWS_S3_ENDPOINT_URL: http://minio:9000
    DATA_DB_HOST: postgres
    DJANGO_SETTINGS_MODULE: contentcuration.settings
    RUN_MODE: docker-compose
    CELERY_TIMEZONE: America/Los_Angeles
    CELERY_REDIS_DB: 0
    CELERY_BROKER_ENDPOINT: redis
    CELERY_RESULT_BACKEND_ENDPOINT: redis
    CELERY_REDIS_PASSWORD: ""
    PROBER_STUDIO_BASE_URL: http://app:8080/{path}

services:
  app:
    image: learningequality/studio-app:prod
    depends_on:
      - minio
      - postgres
      - redis
    environment: *studio-environment
    command: make gunicornserver

  worker:
    image: learningequality/studio-app:prod
    depends_on:
      - minio
      - postgres
      - redis
    environment: *studio-environment
    command: make prodceleryworkers

  nginx:
    image: learningequality/studio-nginx:prod
    environment:
      STUDIO_UPSTREAM_HOST: app
      STUDIO_UPSTREAM_PORT: 8080
      AWS_S3_ENDPOINT_URL: http://minio:9000
      AWS_S3_BUCKET_NAME: http://minio:9000
    depends_on:
      - app
    ports:
      - "8080:8080"

  minio:
    image: minio/minio:RELEASE.2020-06-22T03-12-50Z
    entrypoint: minio server /data
    environment:
      MINIO_ACCESS_KEY: development
      MINIO_SECRET_KEY: development
      MINIO_API_CORS_ALLOW_ORIGIN: http://localhost:8080
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:9.6
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: learningequality
      POSTGRES_PASSWORD: kolibri
      POSTGRES_DB: kolibri-studio
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:4.0.9

  prober:
    image: learningequality/studio-prober:prod
    environment: *studio-environment
    working_dir: /src/deploy
    entrypoint: ""
    # sleep 30 seconds allowing some time for the studio app to start up
    command: '/bin/bash -c "sleep 30 && /bin/cloudprober --config_file ./cloudprober.cfg"'
    # wait until the main app and celery worker have started
    depends_on:
      - app
      - worker


volumes:
  minio_data:
  pgdata:
