# this is meant to be mounted as a folder in the filesystem vs. env vars for studio-secrets.yaml
{{- if .Values.minio.externalGoogleCloudStorage.gcsKeyJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "studio.fullname" . }}-gcs
  labels:
    app: {{ template "studio.name" . }}
    chart: {{ template "studio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  gcs_key.json: {{ .Values.minio.externalGoogleCloudStorage.gcsKeyJson }}
{{- end }}
