apiVersion: v1
kind: Secret
metadata:
  name: {{ template "studio.fullname" . }}
  labels:
    app: studio
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postmark-api-key: {{ .Values.studioApp.postmarkApiKey | default "" | b64enc }}
